# This Dockerfile is used to build the robotic-rovers-proxy image locally
#
# This is not meant to be used in production, it is only for local development purposess
FROM nginx:1.27.2

COPY ./packages/robotic-rovers-proxy/nginx.conf /etc/nginx/nginx.conf